config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  
  get 'welcome/index'

  resources :meals
  resources :foods
  resources :portions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family.rb
class Family < ApplicationRecord
end

app/models/food.rb
class Food < ApplicationRecord

  # food <--> portion
  has_many :portions

  # food <--> meal
  has_many :meals, :through => :portions
end

app/models/meal.rb
class Meal < ApplicationRecord

  # meal <--> portion
  belongs_to :portions

  # meal <--> food
  has_many :foods, :through => :portions

  # meal <--> moment
  belongs_to :moment
  
end

app/models/moment.rb
class Moment < ApplicationRecord

    # moment <--> meal
    has_many :meals
    
end

app/models/portion.rb
class Portion < ApplicationRecord

  validates :weight, presence: true

  # portion <--> meal
  belongs_to :meal, optional: true

  # portion <--> food
  belongs_to :food, optional: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :carbs, :proteins, :fats)
    end
end

app/controllers/moments_controller.rb
class MomentsController < ApplicationController

app/controllers/portion_controller.rb
class PortionsController < ApplicationController

def index
   @portions = Portion.all
end

def new
  @portion = Portion.new
end

def create
  @portion = Portion.new(portion_params)

  respond_to do |format|
    if @portion.save
       format.html {redirect_to @portion, notice: 'Portion created successfully'}
    else
      puts @portion.errors.inpes
       format.html {render :new}
    end
  end

end

def show
  @portion = Portion.find(params[:id])
end

def destroy
  @portion = Portion.find(params[:id])
  @portion.destroy
  respond_to do |format|
    format.html { redirect_to portions_url, notice: 'Portion was successfully destroyed.' }
    format.json { head :no_content }
  end
end

def portion_params
  params.require(:portion).permit(:weight, :food_id)
end

end

app/controllers/portions_controller.rb
class PortionsController < ApplicationController

def index
   @portions = Portion.all
end

def new
  @portion = Portion.new
end

def create
  @portion = Portion.new(portion_params)

  respond_to do |format|
    if @portion.save
       format.html {redirect_to @portion, notice: 'Portion created successfully'}
    else
      puts @portion.errors.inpes
       format.html {render :new}
    end
  end

end

def show
  @portion = Portion.find(params[:id])
end

def destroy
  @portion = Portion.find(params[:id])
  @portion.destroy
  respond_to do |format|
    format.html { redirect_to portions_url, notice: 'Portion was successfully destroyed.' }
    format.json { head :no_content }
  end
end

def portion_params
  params.require(:portion).permit(:weight, :food_id, :meal_id)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/moments_helper.rb
module MomentsHelper
end

app/helpers/portion_helper.rb
module PortionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/foods/_form.html.erb
<%= simple_form_for(food) do |f| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.input :carbs, collection: 0..100 %>
  </div>

  <div class="field">
    <%= f.input :proteins, collection: 0..100 %>
  </div>

  <div class="field">
    <%= f.input :fats, collection: 0..100 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Family</th>
      <th>Carbs</th>
      <th>Proteins</th>
      <th>Fats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.family %></td>
        <td><%= food.carbs %></td>
        <td><%= food.proteins %></td>
        <td><%= food.fats %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Family:</strong>
  <%= @food.family %>
</p>

<p>
  <strong>Carbs:</strong>
  <%= @food.carbs %>
</p>

<p>
  <strong>Proteins:</strong>
  <%= @food.proteins %>
</p>

<p>
  <strong>Fats:</strong>
  <%= @food.fats %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
  <head>
    <title>Meal Diary</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h2>HEADER</h2>

    <header>
      <nav>
        <ul>
          <li><%= link_to_unless_current "Home", :controller => "welcome", :action => "index" %> </li>
          <li><%= link_to_unless_current "Foods", :controller => "foods", :action => "index" %></li>
        </ul>
      </nav>
    </header>

<h1><%= Time.now.strftime("%d/%m/%Y") %></h1>

<% Moment.all.each do |moment| %>
  <div>
    <h2><%= moment.name %></h2>
    <ul>
      <li><%= link_to "New Portion", :controller => "portions", :action => "new" %></li>
      <li><%= link_to "Portion's List", :controller => "portions", :action => "index" %></li>
    </ul>
  </div>
<% end %>


  <body>
    <%= yield %>
  </body>
</html>

app/views/portions/create.html.erb
<h1>Portion#create</h1>
<p>Find me in app/views/portion/create.html.erb</p>

app/views/portions/delete.html.erb
<h1>Portion#delete</h1>
<p>Find me in app/views/portion/delete.html.erb</p>

app/views/portions/index.html.erb
<h1>Portion#index</h1>
<p>Listado</p>
<table>
  <tr>
    <td>Portion id</td>
    <td>Weight</td>
    <td>Food</td>
    <td>Carbs</td>
    <td>Proteins</td>
    <td>Fats</td>
  </tr>

  <% @portions.each do |portion| %>
  <tr>
    <td><%= portion.id %></td>
    <td><%= portion.weight %></td>
    <td><%= portion.food.nil? ? "No hay comida" : portion.food.name %></td>
    <td><%= portion.food.nil? ? "No valid" : (portion.weight*portion.food.carbs)/100%></td>
    <td><%= portion.food.nil? ? "No valid" : (portion.weight*portion.food.proteins)/100%></td>
    <td><%= portion.food.nil? ? "No valid" : (portion.weight*portion.food.fats)/100%></td>
  </tr>
  <% end %>
</table>

app/views/portions/new.html.erb
<h1>Create a new portion</h1>

<%= simple_form_for @portion, :url => {:action=>:create} do |f| %>

<%= f.input :weight, collection: 1..1000 %>
<%= f.collection_select :food_id, Food.all.sort_by(&:name), :id, :name %>
<%= f.button :submit %>

<% end %>

app/views/portions/show.html.erb
<h1>Portion#show</h1>
<p>Find me in app/views/portion/show.html.erb</p>

app/views/portions/view.html.erb
<h1>Portion#view</h1>
<p>Find me in app/views/portion/view.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>